// Used Google Icons
export enum GIcon {
  garage = 'garage',
  balcon = 'balcony',
  jardin = 'yard',
  terrasse = 'deck',
  piscine = 'pool',
  ascenseur = 'elevator',
  piece = 'nest_multi_room',
  chambre = 'bed',
  sallesDeBain = 'baby_changing_station',
  sallesDeau = 'bathroom',
  position = 'location_on',
  phone = 'call',
  euro = 'euro',
  camera = 'photo_camera',
  person = 'person',
  mail = 'mail',
  edit = 'edit',
  pin_drop = 'pin_drop',
  square = 'crop_square',
  calendar = 'calendar_month',
  meuble = 'chair',
}

// Used Primeng Icons
export enum PIcon {
  search = 'pi pi-search',
  info = 'pi pi-info-circle',
  warn = 'pi pi-exclamation-triangle',
  plus = 'pi pi-plus',
  minus = 'pi pi-minus',
  edit = 'pi pi-pencil',
  cog = 'pi pi-cog',
  building = 'pi pi-building',
  lock = 'pi pi-lock',
  eye = 'pi pi-eye',
  eye_slash = 'pi pi-eye-slash',
  trash = 'pi pi-trash',
  user = 'pi pi-user',
  whatsapp = 'pi pi-whatsapp',
  sign_out = 'pi pi-sign-out',
  sign_in = 'pi pi-sign-in',
  user_plus = 'pi pi-user-plus',
}
